ovms.exe ^
  --model_repository_path models ^
  --source_model OpenVINO/Qwen3-8B-int4-cw-ov ^
  --model_name OpenVINO/Qwen3-8B-int4-cw-ov ^
  --target_device NPU ^
  --task text_generation ^
  --tool_parser hermes3 ^
  --cache_dir .ov_cache ^
  --enable_prefix_caching true ^
  --max_prompt_len 4096 ^
  --rest_port 9000